# This input_config.yml file can be used as a template within your own INPUT directory
# Please ensure that the path to the data files are at the SAME LEVEL or SUB-DIRECTORY level as the input_config.yml file (INPUT_directory).
data_files:
  # historical_climate: "./historical_climate_data_new.rds" #use for shapefiles
  historical_climate: "./bien_historical_climate_data.rds" #use for bien ranges
  # future_climate: "./future_climate_data_new.rds" #use for shapefiles
  future_climate: "./bien_future_climate_data.rds" #use for bien ranges
  species: "/Users/ishikakhandelwal/Desktop/home/bsc23001/projects/bien_ranges/processed" #use for bien ranges, write your own path
  # species: "./species_new.rds" #use for shapefiles
species_type: "bien" #shp for shapefiles, bien for bien ranges
exposure_result_file: "exposure_result.rds"
# workers: 1   # This parameter can be used to use a specific number of workers instead of the system default
plan_type: "multisession"
